apps/website/urls.py
from django.urls import path

from apps.website import views as website_views
from apps.user import views as user_views

app_name = "website"

urlpatterns = [
    path("", website_views.HomeView.as_view(), name="home"),
    path(
        "products/paperless/", website_views.PaperLessView.as_view(), name="paperless"
    ),
    path(
        "products/business-insight/",
        website_views.BusinessInsightView.as_view(),
        name="business-insight",
    ),
    path(
        "products/customer-segmentation/",
        website_views.CustomerSegmentation.as_view(),
        name="customer-segmentation",
    ),
    path(
        "products/sales-forecast/",
        website_views.SalesForecast.as_view(),
        name="sales-forecast",
    ),
    # path(
    #     "products/business-insight/",
    #     website_views.BusinessInsightView.as_view(),
    #     name="business-insight",
    # ),
    # ===========================
    # Pricing
    # ===========================
    path("pricing/", website_views.PricingView.as_view(), name="pricing"),
    # ===========================
    # Invoice
    # ===========================
    path("invoice/", website_views.InvoiceView.as_view(), name="invoice"),
    # ===========================
    # auth
    # ===========================
    path("login/", user_views.WebsiteLoginView.as_view(), name="login"),
    path("signup/", user_views.WebsiteSignupView.as_view(), name="signup"),
    path(
        "password-forgot/",
        user_views.WebsitePasswordForgotView.as_view(),
        name="password-forgot",
    ),
    # ===========================
    # Term Policy
    # ===========================
    path("term-policy/", website_views.TermPolicyView.as_view(), name="term-policy"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("tinymce/", include("tinymce.urls")),
    path("dashboard/", include("apps.dashboard.urls")),
    path("", include("apps.website.urls")),
]


if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
        path("__reload__/", include("django_browser_reload.urls")),
    ]

apps/website/models.py
from django.db import models

# Create your models here.

apps/website/views.py
from django.views import generic


class HomeView(generic.TemplateView):
    template_name = "website/home/home.html"


class PaperLessView(generic.TemplateView):
    template_name = "website/products/paperless/index.html"


class BusinessInsightView(generic.TemplateView):
    template_name = "website/products/business_insights/index.html"


class CustomerSegmentation(generic.TemplateView):
    template_name = "website/products/customer_segmentation/index.html"


class SalesForecast(generic.TemplateView):
    template_name = "website/products/sales_forecast/index.html"


class PricingView(generic.TemplateView):
    template_name = "website/pricing/index.html"


class InvoiceView(generic.TemplateView):
    template_name = "website/invoice/index.html"


class TermPolicyView(generic.TemplateView):
    template_name = "website/term_policy.html"

templates/website/_partial/footer.html
<footer class="footer footer-transparent d-print-none">
    <div class="container-xl">
      <div class="row text-center align-items-center flex-row-reverse">
        <div class="col-lg-auto ms-lg-auto">
          <ul class="list-inline list-inline-dots mb-0">
            <li class="list-inline-item">License</li>
            {% comment %} <li class="list-inline-item"><a href="https://github.com/tabler/tabler" target="_blank" class="link-secondary" rel="noopener">Source code</a></li>
            <li class="list-inline-item">
              <a href="https://github.com/sponsors/codecalm" target="_blank" class="link-secondary" rel="noopener">
                <!-- Download SVG icon from http://tabler-icons.io/i/heart -->
                <svg xmlns="http://www.w3.org/2000/svg" class="icon text-pink icon-filled icon-inline" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"></path><path d="M19.5 12.572l-7.5 7.428l-7.5 -7.428a5 5 0 1 1 7.5 -6.566a5 5 0 1 1 7.5 6.572"></path></svg>
                Sponsor
              </a>
            </li> {% endcomment %}
          </ul>
        </div>
        <div class="col-12 col-lg-auto mt-3 mt-lg-0">
          <ul class="list-inline list-inline-dots mb-0">
            <li class="list-inline-item">
              Copyright © 2023
              <a href="." class="link-secondary">Segmenta</a>.
              All rights reserved.
            </li>
            <li class="list-inline-item">
            </li>
          </ul>
        </div>
      </div>
    </div>
  </footer>

templates/website/_partial/full_header.html
{% load static %}
<header class="navbar navbar-dark navbar-expand-md navbar-overlap d-print-none" data-bs-theme="dark">
  <div class="container-xl">
    <button class="navbar-toggler collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#navbar-menu" aria-controls="navbar-menu" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
    <h1 class="navbar-brand navbar-brand-autodark d-none-navbar-horizontal pe-0 pe-md-3"><a href="{% url 'website:home' %}"><img src="{% static 'images/logo.svg' %}" width="110" height="32" alt="Tabler" class="navbar-brand-image" /></a></h1>
    <div class="navbar-collapse collapse" id="navbar-menu" style="">
      <div class="d-flex flex-column flex-md-row flex-fill align-items-stretch align-items-md-center">
        <ul class="navbar-nav ms-md-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'website:home' %}">
              <span class="nav-link-icon d-md-none d-lg-inline-block">
                <!-- Download SVG icon from http://tabler-icons.io/i/home -->
                <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                  <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                  <path d="M5 12l-2 0l9 -9l9 9l-2 0"></path>
                  <path d="M5 12v7a2 2 0 0 0 2 2h10a2 2 0 0 0 2 -2v-7"></path>
                  <path d="M9 21v-6a2 2 0 0 1 2 -2h2a2 2 0 0 1 2 2v6"></path>
                </svg>
              </span>
              <span class="nav-link-title">Home</span>
            </a>
          </li>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#navbar-base" data-bs-toggle="dropdown" data-bs-auto-close="outside" role="button" aria-expanded="false">
              <span class="nav-link-icon d-md-none d-lg-inline-block">
                <!-- Download SVG icon from http://tabler-icons.io/i/package -->
                <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                  <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                  <path d="M12 3l8 4.5l0 9l-8 4.5l-8 -4.5l0 -9l8 -4.5"></path>
                  <path d="M12 12l8 -4.5"></path>
                  <path d="M12 12l0 9"></path>
                  <path d="M12 12l-8 -4.5"></path>
                  <path d="M16 5.25l-8 4.5"></path>
                </svg>
              </span>
              <span class="nav-link-title">Products</span>
            </a>
            <div class="dropdown-menu">
              <div class="dropdown-menu-columns">
                <div class="dropdown-menu-column">
                  <a class="dropdown-item" href="{% url 'website:paperless' %}">Paperless</a>
                  <a class="dropdown-item" href="{% url 'website:business-insight' %}">Business insight</a>
                  <a class="dropdown-item" href="{% url 'website:customer-segmentation' %}">Customer segmentation</a>
                  <a class="dropdown-item" href="{% url 'website:sales-forecast' %}">Sales forecast</a>
                </div>
              </div>
            </div>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'website:pricing' %}">
              <span class="nav-link-icon d-md-none d-lg-inline-block">
                <!-- Download SVG icon from http://tabler-icons.io/i/home -->
                <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-receipt-2" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                  <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                  <path d="M5 21v-16a2 2 0 0 1 2 -2h10a2 2 0 0 1 2 2v16l-3 -2l-2 2l-2 -2l-2 2l-2 -2l-3 2" />
                  <path d="M14 8h-2.5a1.5 1.5 0 0 0 0 3h1a1.5 1.5 0 0 1 0 3h-2.5m2 0v1.5m0 -9v1.5" />
                </svg>
              </span>
              <span class="nav-link-title">Pricing</span>
            </a>
          </li>
          {% if not user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'website:login' %}">
              <span class="nav-link-icon d-md-none d-lg-inline-block">
                <!-- Download SVG icon from http://tabler-icons.io/i/checkbox -->
                <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                  <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                  <path d="M9 11l3 3l8 -8"></path>
                  <path d="M20 12v6a2 2 0 0 1 -2 2h-12a2 2 0 0 1 -2 -2v-12a2 2 0 0 1 2 -2h9"></path>
                </svg>
              </span>
              <span class="nav-link-title">Login</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'website:signup' %}">
              <span class="nav-link-icon d-md-none d-lg-inline-block">
                <!-- Download SVG icon from http://tabler-icons.io/i/checkbox -->
                <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                  <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                  <path d="M9 11l3 3l8 -8"></path>
                  <path d="M20 12v6a2 2 0 0 1 -2 2h-12a2 2 0 0 1 -2 -2v-12a2 2 0 0 1 2 -2h9"></path>
                </svg>
              </span>
              <span class="nav-link-title">SignUp</span>
            </a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
    {% if user.is_authenticated  %}
      <div class="navbar-nav flex-row order-md-last ms-3">
        <div class="nav-item dropdown">
          <a href="#" class="nav-link d-flex lh-1 text-reset p-0" data-bs-toggle="dropdown" aria-label="Open user menu">
            <span class="avatar avatar-sm" style="background-image: url({% static 'images/user.webp' %})"></span>
            <div class="d-none d-xl-block ps-2">
              <div>{{ user.username }}</div>
              <div class="mt-1 small text-secondary">Client</div>
            </div>
          </a>
          <div class="dropdown-menu dropdown-menu-end dropdown-menu-arrow">
            <a href="#" class="dropdown-item" data-bs-toggle="modal" data-bs-target="#logout-model">Logout</a>
          </div>
        </div>
      </div>
    {% endif %}
  </div>
</header>

templates/website/_partial/messages.html
{% if messages %}
    <div class="p-2">
        {% for message in messages %}
            <div    {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                class="alert alert-danger alert-dismissible"
            {% elif message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
                class="alert alert-success alert-dismissible"
            {% endif %}
                role="alert">
                <div class="d-flex">
                    <div>
                        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                            <svg xmlns="http://www.w3.org/2000/svg" class="icon alert-icon" width="24"
                                 height="24"
                                 viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none"
                                 stroke-linecap="round" stroke-linejoin="round">
                                <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                                <path d="M3 12a9 9 0 1 0 18 0a9 9 0 0 0 -18 0"></path>
                                <path d="M12 8v4"></path>
                                <path d="M12 16h.01"></path>
                            </svg>
                        {% elif message.level == DEFAULT_MESSAGE_LEVELS.success %}
                            <svg xmlns="http://www.w3.org/2000/svg" class="icon alert-icon" width="24"
                                 height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor"
                                 fill="none" stroke-linecap="round" stroke-linejoin="round">
                                <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                                <path d="M5 12l5 5l10 -10"></path>
                            </svg>
                        {% endif %}
                    </div>
                    <div>
                        {{ message }}
                    </div>
                </div>
                <a class="btn-close" data-bs-dismiss="alert" aria-label="close"></a>
            </div>
        {% endfor %}
    </div>
{% endif %}

templates/website/_partial/navbar.html
<div class="navbar-collapse collapse" id="navbar-menu" style="">
  <div class="d-flex flex-column flex-md-row flex-fill align-items-stretch align-items-md-center">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="./">
          <span class="nav-link-icon d-md-none d-lg-inline-block">
            <!-- Download SVG icon from http://tabler-icons.io/i/home -->
            <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
              <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
              <path d="M5 12l-2 0l9 -9l9 9l-2 0"></path>
              <path d="M5 12v7a2 2 0 0 0 2 2h10a2 2 0 0 0 2 -2v-7"></path>
              <path d="M9 21v-6a2 2 0 0 1 2 -2h2a2 2 0 0 1 2 2v6"></path>
            </svg>
          </span>
          <span class="nav-link-title">Home</span>
        </a>
      </li>
      <li class="nav-item me-4">
        <a class="nav-link" href="./form-elements.html"><span class="nav-link-title">Prices</span></a>
      </li>
      <li class="nav-item me-2">
        <a class="nav-link btn btn-dark py-0" href="./form-elements.html"><span class="nav-link-title">Login</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link btn btn-dark py-0" href="./form-elements.html"><span class="nav-link-title">SignUp</span></a>
      </li>
    </ul>
  </div>
  <div class="navbar-nav flex-row order-md-last">
    <div class="nav-item d-none d-md-flex me-3">
      <div class="btn-list">
        <a href="https://github.com/tabler/tabler" class="btn" target="_blank" rel="noreferrer">
          <!-- Download SVG icon from http://tabler-icons.io/i/brand-github -->
          <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"></path><path d="M9 19c-4.3 1.4 -4.3 -2.5 -6 -3m12 5v-3.5c0 -1 .1 -1.4 -.5 -2c2.8 -.3 5.5 -1.4 5.5 -6a4.6 4.6 0 0 0 -1.3 -3.2a4.2 4.2 0 0 0 -.1 -3.2s-1.1 -.3 -3.5 1.3a12.3 12.3 0 0 0 -6.2 0c-2.4 -1.6 -3.5 -1.3 -3.5 -1.3a4.2 4.2 0 0 0 -.1 3.2a4.6 4.6 0 0 0 -1.3 3.2c0 4.6 2.7 5.7 5.5 6c-.6 .6 -.6 1.2 -.5 2v3.5"></path></svg>
          Source code
        </a>
        <a href="https://github.com/sponsors/codecalm" class="btn" target="_blank" rel="noreferrer">
          <!-- Download SVG icon from http://tabler-icons.io/i/heart -->
          <svg xmlns="http://www.w3.org/2000/svg" class="icon text-pink" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"></path><path d="M19.5 12.572l-7.5 7.428l-7.5 -7.428a5 5 0 1 1 7.5 -6.566a5 5 0 1 1 7.5 6.572"></path></svg>
          Sponsor
        </a>
      </div>
    </div>
    <div class="d-none d-md-flex">
      <a href="?theme=dark" class="nav-link px-0 hide-theme-dark" data-bs-toggle="tooltip" data-bs-placement="bottom" aria-label="Enable dark mode" data-bs-original-title="Enable dark mode">
        <!-- Download SVG icon from http://tabler-icons.io/i/moon -->
        <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"></path><path d="M12 3c.132 0 .263 0 .393 0a7.5 7.5 0 0 0 7.92 12.446a9 9 0 1 1 -8.313 -12.454z"></path></svg>
      </a>
      <a href="?theme=light" class="nav-link px-0 hide-theme-light" data-bs-toggle="tooltip" data-bs-placement="bottom" aria-label="Enable light mode" data-bs-original-title="Enable light mode">
        <!-- Download SVG icon from http://tabler-icons.io/i/sun -->
        <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"></path><path d="M12 12m-4 0a4 4 0 1 0 8 0a4 4 0 1 0 -8 0"></path><path d="M3 12h1m8 -9v1m8 8h1m-9 8v1m-6.4 -15.4l.7 .7m12.1 -.7l-.7 .7m0 11.4l.7 .7m-12.1 -.7l-.7 .7"></path></svg>
      </a>
      <div class="nav-item dropdown d-none d-md-flex me-3">
        <a href="#" class="nav-link px-0" data-bs-toggle="dropdown" tabindex="-1" aria-label="Show notifications">
          <!-- Download SVG icon from http://tabler-icons.io/i/bell -->
          <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"></path><path d="M10 5a2 2 0 1 1 4 0a7 7 0 0 1 4 6v3a4 4 0 0 0 2 3h-16a4 4 0 0 0 2 -3v-3a7 7 0 0 1 4 -6"></path><path d="M9 17v1a3 3 0 0 0 6 0v-1"></path></svg>
          <span class="badge bg-red"></span>
        </a>
        <div class="dropdown-menu dropdown-menu-arrow dropdown-menu-end dropdown-menu-card">
          <div class="card">
            <div class="card-header">
              <h3 class="card-title">Last updates</h3>
            </div>
            <div class="list-group list-group-flush list-group-hoverable">
              <div class="list-group-item">
                <div class="row align-items-center">
                  <div class="col-auto"><span class="status-dot status-dot-animated bg-red d-block"></span></div>
                  <div class="col text-truncate">
                    <a href="#" class="text-body d-block">Example 1</a>
                    <div class="d-block text-secondary text-truncate mt-n1">
                      Change deprecated html tags to text decoration classes (#29604)
                    </div>
                  </div>
                  <div class="col-auto">
                    <a href="#" class="list-group-item-actions">
                      <!-- Download SVG icon from http://tabler-icons.io/i/star -->
                      <svg xmlns="http://www.w3.org/2000/svg" class="icon text-muted" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"></path><path d="M12 17.75l-6.172 3.245l1.179 -6.873l-5 -4.867l6.9 -1l3.086 -6.253l3.086 6.253l6.9 1l-5 4.867l1.179 6.873z"></path></svg>
                    </a>
                  </div>
                </div>
              </div>
              <div class="list-group-item">
                <div class="row align-items-center">
                  <div class="col-auto"><span class="status-dot d-block"></span></div>
                  <div class="col text-truncate">
                    <a href="#" class="text-body d-block">Example 2</a>
                    <div class="d-block text-secondary text-truncate mt-n1">
                      justify-content:between ⇒ justify-content:space-between (#29734)
                    </div>
                  </div>
                  <div class="col-auto">
                    <a href="#" class="list-group-item-actions show">
                      <!-- Download SVG icon from http://tabler-icons.io/i/star -->
                      <svg xmlns="http://www.w3.org/2000/svg" class="icon text-yellow" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"></path><path d="M12 17.75l-6.172 3.245l1.179 -6.873l-5 -4.867l6.9 -1l3.086 -6.253l3.086 6.253l6.9 1l-5 4.867l1.179 6.873z"></path></svg>
                    </a>
                  </div>
                </div>
              </div>
              <div class="list-group-item">
                <div class="row align-items-center">
                  <div class="col-auto"><span class="status-dot d-block"></span></div>
                  <div class="col text-truncate">
                    <a href="#" class="text-body d-block">Example 3</a>
                    <div class="d-block text-secondary text-truncate mt-n1">
                      Update change-version.js (#29736)
                    </div>
                  </div>
                  <div class="col-auto">
                    <a href="#" class="list-group-item-actions">
                      <!-- Download SVG icon from http://tabler-icons.io/i/star -->
                      <svg xmlns="http://www.w3.org/2000/svg" class="icon text-muted" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"></path><path d="M12 17.75l-6.172 3.245l1.179 -6.873l-5 -4.867l6.9 -1l3.086 -6.253l3.086 6.253l6.9 1l-5 4.867l1.179 6.873z"></path></svg>
                    </a>
                  </div>
                </div>
              </div>
              <div class="list-group-item">
                <div class="row align-items-center">
                  <div class="col-auto"><span class="status-dot status-dot-animated bg-green d-block"></span></div>
                  <div class="col text-truncate">
                    <a href="#" class="text-body d-block">Example 4</a>
                    <div class="d-block text-secondary text-truncate mt-n1">
                      Regenerate package-lock.json (#29730)
                    </div>
                  </div>
                  <div class="col-auto">
                    <a href="#" class="list-group-item-actions">
                      <!-- Download SVG icon from http://tabler-icons.io/i/star -->
                      <svg xmlns="http://www.w3.org/2000/svg" class="icon text-muted" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"></path><path d="M12 17.75l-6.172 3.245l1.179 -6.873l-5 -4.867l6.9 -1l3.086 -6.253l3.086 6.253l6.9 1l-5 4.867l1.179 6.873z"></path></svg>
                    </a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="nav-item dropdown">
      <a href="#" class="nav-link d-flex lh-1 text-reset p-0" data-bs-toggle="dropdown" aria-label="Open user menu">
        <span class="avatar avatar-sm" style="background-image: url(./static/avatars/000m.jpg)"></span>
        <div class="d-none d-xl-block ps-2">
          <div>Paweł Kuna</div>
          <div class="mt-1 small text-secondary">UI Designer</div>
        </div>
      </a>
      <div class="dropdown-menu dropdown-menu-end dropdown-menu-arrow">
        <a href="#" class="dropdown-item">Status</a>
        <a href="./profile.html" class="dropdown-item">Profile</a>
        <a href="#" class="dropdown-item">Feedback</a>
        <div class="dropdown-divider"></div>
        <a href="./settings.html" class="dropdown-item">Settings</a>
        <a href="./sign-in.html" class="dropdown-item">Logout</a>
      </div>
    </div>
  </div>
</div>