apps/dashboard/urls.py
from django.urls import path

from apps.dashboard import views as dashboard_views
from apps.user import views as user_views

app_name = "dashboard"

urlpatterns = [
    path("", dashboard_views.Home.as_view(), name="home"),
    # ============================
    # USER
    # ============================
    path("users/", user_views.DashboardUserListView.as_view(), name="user-list"),
    path(
        "users/create/",
        user_views.DashboardUserCreateView.as_view(),
        name="user-create",
    ),
    path(
        "users/<int:pk>/update/",
        user_views.DashboardUserUpdateView.as_view(),
        name="user-update",
    ),
    # ============================
    # Settings
    # ============================
    path(
        "settings/",
        dashboard_views.DashboardSettingsSectionView.as_view(),
        name="settings",
    ),
    # ============================
    # AUTH
    # ============================
    path("login/", user_views.DashboardLoginView.as_view(), name="login"),
    path("logout/", user_views.DashboardLogoutView.as_view(), name="logout"),
]

apps/website/urls.py
from django.urls import path

from apps.website import views as website_views
from apps.user import views as user_views

app_name = "website"

urlpatterns = [
    path("", website_views.HomeView.as_view(), name="home"),
    path(
        "products/paperless/", website_views.PaperLessView.as_view(), name="paperless"
    ),
    path(
        "products/business-insight/",
        website_views.BusinessInsightView.as_view(),
        name="business-insight",
    ),
    path(
        "products/customer-segmentation/",
        website_views.CustomerSegmentation.as_view(),
        name="customer-segmentation",
    ),
    path(
        "products/sales-forecast/",
        website_views.SalesForecast.as_view(),
        name="sales-forecast",
    ),
    # path(
    #     "products/business-insight/",
    #     website_views.BusinessInsightView.as_view(),
    #     name="business-insight",
    # ),
    # ===========================
    # Pricing
    # ===========================
    path("pricing/", website_views.PricingView.as_view(), name="pricing"),
    # ===========================
    # Invoice
    # ===========================
    path("invoice/", website_views.InvoiceView.as_view(), name="invoice"),
    # ===========================
    # auth
    # ===========================
    path("login/", user_views.WebsiteLoginView.as_view(), name="login"),
    path("signup/", user_views.WebsiteSignupView.as_view(), name="signup"),
    path(
        "password-forgot/",
        user_views.WebsitePasswordForgotView.as_view(),
        name="password-forgot",
    ),
    # ===========================
    # Term Policy
    # ===========================
    path("term-policy/", website_views.TermPolicyView.as_view(), name="term-policy"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("tinymce/", include("tinymce.urls")),
    path("dashboard/", include("apps.dashboard.urls")),
    path("", include("apps.website.urls")),
]


if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
        path("__reload__/", include("django_browser_reload.urls")),
    ]

apps/website/models.py
from django.db import models

# Create your models here.

apps/website/views.py
from django.views import generic


class HomeView(generic.TemplateView):
    template_name = "website/home/home.html"


class PaperLessView(generic.TemplateView):
    template_name = "website/products/paperless/index.html"


class BusinessInsightView(generic.TemplateView):
    template_name = "website/products/business_insights/index.html"


class CustomerSegmentation(generic.TemplateView):
    template_name = "website/products/customer_segmentation/index.html"


class SalesForecast(generic.TemplateView):
    template_name = "website/products/sales_forecast/index.html"


class PricingView(generic.TemplateView):
    template_name = "website/pricing/index.html"


class InvoiceView(generic.TemplateView):
    template_name = "website/invoice/index.html"


class TermPolicyView(generic.TemplateView):
    template_name = "website/term_policy.html"

templates/website/base.html
{% extends "dashboard/template.html" %}
{% load static %}

{% block css_link %}
{#    <style>#}
{#        @font-face {#}
{#            font-family: "Rubik";#}
{#            src: url("{% static "fonts/rubik/Rubik-Regular.ttf" %}");#}
{#        }#}
{##}
{#        @font-face {#}
{#            font-family: "Rubik";#}
{#            src: url("{% static "fonts/rubik/Rubik-Light.ttf" %}");#}
{#            font-weight: 300;#}
{#        }#}
{##}
{#        @font-face {#}
{#            font-family: "Rubik";#}
{#            src: url("{% static "fonts/rubik/Rubik-SemiBold.ttf" %}");#}
{#            font-weight: bold;#}
{#        }#}
{##}
{#        @font-face {#}
{#            font-family: "Rubik";#}
{#            src: url("{% static "fonts/rubik/Rubik-Medium.ttf" %}");#}
{#            font-weight: 500;#}
{#        }#}
{##}
{#        *{#}
{#            font-family: 'Rubik';#}
{#        }#}
{#    </style>#}
    <link rel="stylesheet" href="{% static 'css/vendor/tabler.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/website.css' %}">
{% endblock %}

{% block body %}
    <div class="page">
        {% include "website/_partial/full_header.html" %}

        <div class="page-wrapper">
            {% block page %}
                    {% include 'dashboard/_partial/messages.html' %}
                {% block page_header %}{% endblock %}
                <div class="page-body">
                    {% block page_body %}
                    {% endblock %}
                    {% block footer %}
                        {% include 'website/_partial/footer.html' %}
                    {% endblock %}
                </div>
            {% endblock %}
        </div>
    </div>
    {% block model %}
        <div class="modal modal-blur fade" id="logout-model" tabindex="-1" style="display: none;" aria-hidden="true">
            <div class="modal-dialog modal-sm modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-body">
                        <div class="modal-title">Are you sure to logout?</div>
                        <div>If you logout you will be redirect to login page.</div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-link link-secondary me-auto" data-bs-dismiss="modal">Cancel
                        </button>
                        <form method="post" action="{% url 'dashboard:logout' %}">
                            {% csrf_token %}
                            <input type="submit" class="btn btn-danger" value="Logout">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    {% endblock model %}


    
{% endblock body %}


{% block js %}
    <script src="{% static 'js/vendor/tabler.min.js' %}"></script>
    <script src="{% static 'js/website.js' %}"></script>
{% endblock %}

templates/website/template.html
    <!doctype html>
    <html class="no-js" lang="">
        <head>
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <meta name="description" content="{{page_description}}">
            <title>{{page_title}}</title>

            {% block meta_content %}
            {% endblock meta_content %}

            {% block favicon %}
            {% endblock favicon %}

            {% block css_link %}
            {% endblock css_link %}

            {% block extra_css_link %}
            {% endblock extra_css_link %}

            {% block css_style %}
            {% endblock css_style %}
        </head>


        <body >
            {% block body %}{% endblock body %}
            {% block models %}{% endblock %}
            {% block js %}{% endblock js %}
            {% block extra_js %}{% endblock extra_js %}
        </body>

    </html>

templates/website/term_policy.html
{% extends 'website/base.html' %}
{% load static %}

{% block page_body %}
<div class="container-xl">
    <div class="row row-cards">
      <div class="col-lg-8 mx-auto">
        <div class="card card-lg">
          <div class="card-body py-4">
            <div class="markdown">
              <h2>Tabler License</h2>
              <p>This is a legal agreement between you, the Purchaser, and Tabler. Purchasing or downloading of any Tabler product (Tabler Free, Tabler PRO, Tabler Email), constitutes your acceptance of the terms of this license, <a href="https://tabler.io/terms-of-service.html">Tabler terms of service</a> and <a href="https://tabler.io/privacy-policy.html">Tabler private policy</a>.</p>
              <p>A license grants you a non-exclusive and non-transferable right to use and incorporate the item in your personal or commercial projects.</p>
              <h3 id="tabler-free-license">Tabler Free License</h3>
              <p>Tabler Free is available under MIT License</p>
              <p>Copyright 2023 Tabler</p>
              <p>Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the “Software”), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:</p>
              <p>The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.</p>
              <p>THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.</p>
              <h3 id="tabler-pro-and-tabler-email-license">Tabler PRO and Tabler Email License</h3>
              <p>After Purchasing you are granted the use products under the conditions featured belowed.</p>
              <p>Rights</p>
              <ol>
                <li>You have rights to use our resources for any or all of your personal and commercial projects.</li>
                <li>You may modify the resources according to your requirements.</li>
                <li>You are not required to attribute or link to Tabler in any of your projects.</li>
              </ol>
              <p>Restrictions</p>
              <ol>
                <li>You do not have the rights to redistribute, resell, lease, license, sub-license or offer the file downloaded to any third party.</li>
                <li>For any resalable web applications or software programs, you cannot include our graphic resources as an additional attachment.</li>
                <li>You cannot redistribute any of the software, or products created with Tabler paid  products.</li>
                <li>You cannot add our source code to any open source repository.</li>
                <li>The source code may not be placed on any website in a complete or archived downloadable format.</li>
              </ol>
            </div>
          </div>
        </div>
      </div>

    </div>
  </div>
{% endblock %}