apps/dashboard/urls.py
from django.urls import path

from apps.dashboard import views as dashboard_views
from apps.user import views as user_views

app_name = "dashboard"

urlpatterns = [
    path("", dashboard_views.Home.as_view(), name="home"),
    # ============================
    # USER
    # ============================
    path("users/", user_views.DashboardUserListView.as_view(), name="user-list"),
    path(
        "users/create/",
        user_views.DashboardUserCreateView.as_view(),
        name="user-create",
    ),
    path(
        "users/<int:pk>/update/",
        user_views.DashboardUserUpdateView.as_view(),
        name="user-update",
    ),
    # ============================
    # Settings
    # ============================
    path(
        "settings/",
        dashboard_views.DashboardSettingsSectionView.as_view(),
        name="settings",
    ),
    # ============================
    # AUTH
    # ============================
    path("login/", user_views.DashboardLoginView.as_view(), name="login"),
    path("logout/", user_views.DashboardLogoutView.as_view(), name="logout"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("tinymce/", include("tinymce.urls")),
    path("dashboard/", include("apps.dashboard.urls")),
    path("", include("apps.website.urls")),
]


if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
        path("__reload__/", include("django_browser_reload.urls")),
    ]

apps/dashboard/models.py
from django.db import models

# Create your models here.

apps/user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, UserManager


class User(AbstractUser):
    class Role(models.TextChoices):
        CLIENT = "CLIENT", "Client"
        SUPERVISOR = "SUPERVISOR", "Supervisor"

    base_role = Role.CLIENT

    role = models.CharField(max_length=50, choices=Role.choices)

    def save(self, *args, **kwargs):
        if not self.pk:
            self.role = self.base_role

        return super().save(*args, **kwargs)


class ClientManager(UserManager):
    def get_queryset(self, *args, **kwargs):
        results = super().get_queryset(*args, **kwargs)
        return results.filter(role=User.Role.CLIENT)


class Client(User):
    base_role = User.Role.CLIENT

    objects = ClientManager()

    class Meta:
        proxy = True


class SupervisorManager(UserManager):
    def get_queryset(self, *args, **kwargs):
        results = super().get_queryset(*args, **kwargs)
        return results.filter(role=User.Role.SUPERVISOR)


class Supervisor(User):
    base_role = User.Role.SUPERVISOR

    objects = SupervisorManager()

    class Meta:
        proxy = True

apps/user/forms.py
from django.contrib.auth.forms import AuthenticationForm
from django import forms
from django.core.exceptions import ValidationError

from apps.user.models import User, Supervisor, Client


class SupervisorAuthenticationForm(AuthenticationForm):
    def confirm_login_allowed(self, user: User):
        print(user.role)
        if not user.role == User.Role.SUPERVISOR:
            raise ValidationError(
                self.error_messages["invalid_login"],
                code="invalid_login",
                params={"username": self.username_field.verbose_name},
            )


class SupervisorCreateForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs["class"] = "form-control"

        # Check if the form is being used for an update view
        if kwargs.get("instance"):
            # If it is, remove the "password" field
            self.fields.pop("password")

    class Meta:
        model = User
        fields = ("username", "email", "password")

    def save(self, commit=True):
        data = self.cleaned_data
        if user := self.instance:
            user.username = data["username"]
            user.email = data["email"]
            user.save()
            return user
        else:
            user = Supervisor.objects.create_user(
                data["username"], data["email"], data["password"]
            )
            return user


class ClientAuthenticationForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for name, field in self.fields.items():
            field.widget.attrs["class"] = "form-control"
            if name == "password":
                field.widget.attrs["placeholder"] = "************"
            else:
                field.widget.attrs["placeholder"] = "Username"

    def confirm_login_allowed(self, user: User):
        print(user.role)
        if not user.role == User.Role.CLIENT:
            raise ValidationError(
                self.error_messages["invalid_login"],
                code="invalid_login",
                params={"username": self.username_field.verbose_name},
            )


class ClientCreateForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs["class"] = "form-control"

    class Meta:
        model = User
        fields = ("username", "email", "password")

    def save(self, commit=...):
        data = self.cleaned_data
        user = Client.objects.create_user(
            data["username"], data["email"], data["password"]
        )
        return user

apps/dashboard/views.py
from django.views import generic


from apps.dashboard.mixins import DashboardMixin, HeaderMixin


class Home(DashboardMixin, generic.TemplateView):
    section_name = "home"
    template_name = "dashboard/main/home.html"


class DashboardSettingsSectionView(DashboardMixin, HeaderMixin, generic.TemplateView):
    header_name = "section"
    section_name = "settings"
    template_name = "dashboard/settings/section.html"

apps/user/views.py
from typing import Any
from django.contrib.auth.views import LoginView, LogoutView
from django.db import models
from django.db.models.query import QuerySet
from django.http import HttpResponse
from django.views import generic
from django.urls import reverse, reverse_lazy


from apps.dashboard.mixins import DashboardMixin
from apps.user.models import Supervisor, Client
from apps.user import forms as user_form


class DashboardLoginView(LoginView):
    template_name = "dashboard/auth/login.html"
    form_class = user_form.SupervisorAuthenticationForm
    next_page = "dashboard:home"


class DashboardLogoutView(LogoutView):
    next_page = "website:login"


class DashboardUserListView(DashboardMixin, generic.ListView):
    section_name = "user"
    template_name = "dashboard/user/list.html"
    paginate_by = 2

    def get_queryset(self) -> QuerySet[Any]:
        return Supervisor.objects.all()


class DashboardUserCreateView(DashboardMixin, generic.CreateView):
    section_name = "user"
    form_class = user_form.SupervisorCreateForm
    template_name = "dashboard/user/form.html"

    def get_success_url(self) -> str:
        return reverse("dashboard:user-list")


class DashboardUserUpdateView(DashboardMixin, generic.UpdateView):
    section_name = "user"
    form_class = user_form.SupervisorCreateForm
    template_name = "dashboard/user/form.html"

    def get_queryset(self) -> QuerySet[Any]:
        return Supervisor.objects.all()

    def get_success_url(self) -> str:
        return reverse("dashboard:user-list")


# ================================================================
# WEBSITE
# ================================================================


class WebsiteLoginView(LoginView):
    template_name = "website/auth/login.html"
    form_class = user_form.ClientAuthenticationForm
    next_page = "website:home"


class WebsiteSignupView(generic.FormView):
    template_name = "website/auth/signup.html"
    next_page = "website:login"
    form_class = user_form.ClientCreateForm
    success_url = reverse_lazy("website:home")

    def form_valid(self, form: Any) -> HttpResponse:
        form.save()
        return super().form_valid(form)


class WebsitePasswordForgotView(generic.TemplateView):
    template_name = "website/auth/password_forgot.html"

templates/dashboard/user/form.html
{% extends 'dashboard/base.html' %}

{% block page_header %}

{% endblock %}

{% block page_body %}
<div class="container-xl">
    <div class="card">
        <div class="card-body">
            <h1>User create</h1>
            <form method="post">
                {% csrf_token %}
                {{form}}
                <div class="d-flex justify-content-end p-2">
                    <input type="submit" class="btn btn-success" value="Save">
                 </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/dashboard/user/list.html
{% extends "dashboard/base.html" %}

{% block page_header %}
<div class="page-header d-print-none">
    <div class="container-xl">
      <div class="row g-2 align-items-center">
        <div class="col">
          <!-- Page pre-title -->
          <div class="page-pretitle">
            Overview
          </div>
          <h2 class="page-title">
            User list
          </h2>
          <ol class="breadcrumb">
            <li class="breadcrumb-item disabled"><a href="#">User list</a></li>
          </ol>
        </div>
        <!-- Page title actions -->
        <div class="col-auto ms-auto d-print-none">
          <div class="btn-list">
            <a href="{% url 'dashboard:user-create' %}" class="btn btn-primary d-none d-sm-inline-block" >
              <!-- Download SVG icon from http://tabler-icons.io/i/plus -->
             
              <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-user-plus" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><path d="M8 7a4 4 0 1 0 8 0a4 4 0 0 0 -8 0" /><path d="M16 19h6" /><path d="M19 16v6" /><path d="M6 21v-2a4 4 0 0 1 4 -4h4" /></svg>

              Create new user
            </a>
            <a href="{% url 'dashboard:user-create' %}" class="btn btn-primary d-sm-none btn-icon" >
              <!-- Download SVG icon from http://tabler-icons.io/i/plus -->
              <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-user-plus" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><path d="M8 7a4 4 0 1 0 8 0a4 4 0 0 0 -8 0" /><path d="M16 19h6" /><path d="M19 16v6" /><path d="M6 21v-2a4 4 0 0 1 4 -4h4" /></svg>

            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock page_header %}


{% block page_body %}
<div class="container-xl">
    <div class="card">
        <div class="card-body border-bottom py-3">
            <div class="d-flex">
                <div class="ms-auto text-secondary">
                    Search:
                    <div class="ms-2 d-inline-block">
                        <input type="text" class="form-control form-control-sm" aria-label="Search invoice">
                    </div>
                </div>
            </div>
        </div>
        <div class="table-responsive">
            <table class="table card-table table-vcenter text-nowrap datatable">
                <thead>
                <tr>
                    <th class="w-1"><input class="form-check-input m-0 align-middle" type="checkbox"
                                           aria-label="Select all invoices"></th>
                    <th class="w-1">No. <!-- Download SVG icon from http://tabler-icons.io/i/chevron-up -->
                        <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-sm icon-thick" width="24"
                             height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none"
                             stroke-linecap="round" stroke-linejoin="round">
                            <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                            <path d="M6 15l6 -6l6 6"></path>
                        </svg>
                    </th>
                    <th>Username</th>
                    <th>email</th>
                    <th>Create date</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                    {% for user in page_obj.object_list %}
                        <tr>
                    <td><input class="form-check-input m-0 align-middle" type="checkbox"
                               aria-label="Select invoice"></td>
                    <td><span class="text-secondary">{{ user.id }}</span></td>
                    <td>{{ user.username }}</td>
                    <td>
                        {{ user.email }}
                    </td>
                    <td>
                        {{ user.create_date }}
                    </td>

                    <td class="text-end">
                        <a href="{% url 'dashboard:user-update' user.pk %}">edit</a>
                    </td>
                </tr>
                    {% endfor %}


                </tbody>
            </table>
        </div>
        <div class="card-footer d-flex align-items-center justify-content-between">
            <p class="m-0 text-secondary">  Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.</p>
            {% include "dashboard/_partial/pagination.html" %}
        </div>
    </div>
</div>
{% endblock %}